// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// rminuit2_cpp
List rminuit2_cpp(SEXP fn, SEXP env, NumericVector par, NumericVector err, NumericVector lower, NumericVector upper, IntegerVector fix, StringVector opt, IntegerVector maxcalls, NumericVector nsigma);
RcppExport SEXP _rminuit2_rminuit2_cpp(SEXP fnSEXP, SEXP envSEXP, SEXP parSEXP, SEXP errSEXP, SEXP lowerSEXP, SEXP upperSEXP, SEXP fixSEXP, SEXP optSEXP, SEXP maxcallsSEXP, SEXP nsigmaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type fn(fnSEXP);
    Rcpp::traits::input_parameter< SEXP >::type env(envSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type par(parSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type err(errSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type lower(lowerSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type upper(upperSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type fix(fixSEXP);
    Rcpp::traits::input_parameter< StringVector >::type opt(optSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type maxcalls(maxcallsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type nsigma(nsigmaSEXP);
    rcpp_result_gen = Rcpp::wrap(rminuit2_cpp(fn, env, par, err, lower, upper, fix, opt, maxcalls, nsigma));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_rminuit2_rminuit2_cpp", (DL_FUNC) &_rminuit2_rminuit2_cpp, 10},
    {NULL, NULL, 0}
};

RcppExport void R_init_rminuit2(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
