# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rminuit2_cpp <- function(fn, env, par, err, lower, upper, fix, opt, maxcalls, nsigma) {
    .Call(`_rminuit2_rminuit2_cpp`, fn, env, par, err, lower, upper, fix, opt, maxcalls, nsigma)
}

