# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rminuit2_cpp <- function(fn, par, err, lower, upper, fix, opt, envir, maxcalls) {
    .Call('_rminuit2_rminuit2_cpp', PACKAGE = 'rminuit2', fn, par, err, lower, upper, fix, opt, envir, maxcalls)
}

